### ISSUE TITLE
Requests package version is out of date

### ISSUE THREAD

**Issue by owencjones** [ONSdigital/response-operations-ui#252]
Requests package is 2.18.4, which is out of date.  Can cause test failure.

**Comment by jcox-dev** [comment]
The packages should probably all be starred ("*") and then a dev should re-lock the packages when making code changes to keep them all up to date.

**Comment by owencjones** [comment]
@jcox-dev Does wildcarding them not risk introducing bugs, or causing out and out failures when features are deprecated etc.?

I'd be more in favour of defaulting to specifying a major version only, and being more precise only when needed.

Thoughts?

**Comment by jcox-dev** [comment]
I think we agreed that to star a package was fine (and what we've done for other repos), as a dev process would be to check for and upgrade out of date packages (`pipenv update`), run tests (to confirm nothing has changed with the upgraded package(s) API(s)), then commit the changes to the Pipfile.

**Comment by owencjones** [comment]
Ok, well I've put in a relatively quick fix for this one, which _doesn't_ take your approach, so I'll open a new issue to change _all_ versions to use the recommended approach.
